##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## Makefile
##

D_SRC	=	./src/

NAME	=	209poll

$(NAME)	:
			cp $(D_SRC)209.py ./
			mv 209.py 209poll
			chmod +x 209poll

all	:	$(NAME)

clean:
		rm -rf 209poll

fclean:	clean

re	:	fclean all

.PHONY: all clean fclean re
